### ISSUE TITLE
provide mongo DB support

### ISSUE THREAD

**Issue by msamgan** [msamgan/expressjs-api-boilerplate#21]

**Comment by msamgan** [comment]
Issue in copy connection file from bin.

**Comment by bilalsha** [comment]
@msamgan Can I fix this issue? let me know

**Comment by msamgan** [comment]
any and all type of support are most welcome.
you can create a PR any time.
thanks

**Comment by msamgan** [comment]
@bilalsha hey bro, are you willing to do it still ?
